from pathlib import Path
p = Path('/home/ubuntu/do-nhay-ff-sua/client/src/pages/Home.tsx')
s = p.read_text()

s = s.replace('  model: string;\n  aliases:', '  model: string;\n  normalizedModel?: string;\n  aliases:')
s = s.replace('type SearchResult = { device: Device; source: "database" | "estimated"; sensitivity: Sensitivity; createdAt: string; };', 'type SearchResult = { device: Device; matchType: "exact-model" | "exact-alias" | "exact-brand-model" | "token" | "fuzzy" | "estimated"; confidence: number; correctedQuery?: string; source: "database" | "estimated"; sensitivity: Sensitivity; createdAt: string; };')

# Add separate Samsung variants and Redmi Note 14 without changing the popular iQOO card.
needle = '  { id: "samsung-s23-ultra", brand: "Samsung", model: "Galaxy S23 Ultra", aliases: ["s23 ultra", "s23u", "galaxy s23 ultra", "samsung s23", "samsung s23 ultra"], type: "PHONE", tier: "FLAGSHIP", refreshRate: 120, touchSampling: 240, ram: 12, processorLevel: 9, os: "Android", score: 95, gradient: "from-cyan-400/20 to-blue-500/5", accent: "#58d6ff" },'
variants = needle + '\n  { id: "samsung-s23", brand: "Samsung", model: "Galaxy S23", aliases: ["s23", "samsung s23", "galaxy s23"], type: "PHONE", tier: "FLAGSHIP", refreshRate: 120, touchSampling: 240, ram: 8, processorLevel: 8, os: "Android", score: 94, gradient: "from-cyan-300/15 to-blue-400/5", accent: "#6edcff" },\n  { id: "samsung-s23-plus", brand: "Samsung", model: "Galaxy S23+", aliases: ["s23+", "s23 plus", "samsung s23 plus", "galaxy s23 plus"], type: "PHONE", tier: "FLAGSHIP", refreshRate: 120, touchSampling: 240, ram: 8, processorLevel: 8, os: "Android", score: 94, gradient: "from-cyan-300/15 to-blue-400/5", accent: "#6edcff" },\n  { id: "samsung-s23-fe", brand: "Samsung", model: "Galaxy S23 FE", aliases: ["s23 fe", "samsung s23 fe", "galaxy s23 fe"], type: "PHONE", tier: "FLAGSHIP", refreshRate: 120, touchSampling: 120, ram: 8, processorLevel: 7, os: "Android", score: 90, gradient: "from-cyan-300/15 to-blue-400/5", accent: "#6edcff" },'
if 'samsung-s23-plus' not in s:
    s = s.replace(needle, variants)

# Add Redmi Note 14 as a distinct database entity.
redmi_needle = '  { id: "redmi-note-13-pro", brand: "Xiaomi", model: "Redmi Note 13 Pro", aliases: ["redmi note 13 pro", "note 13 pro", "redmi 13 pro"], type: "PHONE", tier: "MIDRANGE", refreshRate: 120, touchSampling: 240, ram: 8, processorLevel: 7, os: "Android", score: 89, gradient: "from-orange-300/20 to-rose-500/5", accent: "#ffb87a" },'
redmi_new = redmi_needle + '\n  { id: "redmi-note-14", brand: "Redmi", model: "Redmi Note 14", aliases: ["note 14", "redmi note14", "redmi note 14"], type: "PHONE", tier: "MIDRANGE", refreshRate: 120, touchSampling: 240, ram: 8, processorLevel: 7, os: "Android", score: 88, gradient: "from-orange-300/20 to-rose-500/5", accent: "#ffb87a" },'
if 'redmi-note-14' not in s:
    s = s.replace(redmi_needle, redmi_new)

start = s.index('function normalize(text: string) {')
end = s.index('\n\nfunction createFallbackDevice', start)
search_code = '''function normalize(text: string) {\n  return text.toLowerCase().normalize("NFD").replace(/[\\u0300-\\u036f]/g, "").replace(/\\s+/g, " ").trim();\n}\n\nfunction compactNormalize(text: string) {\n  return normalize(text).replace(/[^a-z0-9+]/g, "");\n}\n\nfunction exactMatchType(query: string, device: Device) {\n  const q = normalize(query);\n  const compact = compactNormalize(query);\n  const model = normalize(device.normalizedModel || device.model);\n  const brandModel = normalize(`${device.brand} ${device.model}`);\n  const aliases = device.aliases.map(normalize);\n  if (q === model || compact === compactNormalize(model)) return "exact-model" as const;\n  if (aliases.some((alias) => q === alias || compact === compactNormalize(alias))) return "exact-alias" as const;\n  if (q === brandModel || compact === compactNormalize(brandModel)) return "exact-brand-model" as const;\n  const queryTokens = q.split(" ").filter(Boolean);\n  const modelTokens = model.split(" ");\n  if (queryTokens.length > 0 && queryTokens.length === modelTokens.length && queryTokens.every((token, index) => token === modelTokens[index])) return "token" as const;\n  return null;\n}\n\nfunction fuzzyScore(query: string, device: Device) {\n  const q = compactNormalize(query);\n  if (!q) return 0;\n  const terms = [device.model, `${device.brand} ${device.model}`, ...device.aliases].map(compactNormalize);\n  return Math.max(...terms.map((term) => {\n    if (term === q) return 100;\n    if (term.startsWith(q)) return 74;\n    if (term.includes(q)) return 58;\n    let common = 0;\n    for (const char of q) if (term.includes(char)) common++;\n    return common / Math.max(q.length, 1) > 0.78 ? 42 : 0;\n  }));\n}\n\nfunction rankedMatches(query: string) {\n  const exact = devices.flatMap((device) => {\n    const matchType = exactMatchType(query, device);\n    return matchType ? [{ device, score: 100, matchType }] : [];\n  });\n  if (exact.length) return exact.sort((a, b) => a.device.model.length - b.device.model.length);\n  return devices.map((device) => ({ device, score: fuzzyScore(query, device), matchType: "fuzzy" as const })).filter((item) => item.score > 0).sort((a, b) => b.score - a.score).slice(0, 4);\n}\n'''
s = s[:start] + search_code + s[end:]

s = s.replace('const matches = useMemo(() => devices.map((device) => ({ device, score: fuzzyScore(debouncedQuery, device) })).filter((item) => item.score > 0).sort((a, b) => b.score - a.score).slice(0, 4), [debouncedQuery]);', 'const matches = useMemo(() => rankedMatches(debouncedQuery), [debouncedQuery]);')

# Pass exact/fuzzy metadata into SearchResult.
s = s.replace('const createdAt = new Date().toISOString();\n      setResult(next);\n      setSearchResult({ device, source: device.id.startsWith("generated-") ? "estimated" : "database", sensitivity: next, createdAt });', 'const createdAt = new Date().toISOString();\n      const matched = exactMatchType(query, device);\n      const matchType = device.id.startsWith("generated-") ? "estimated" : (matched || "fuzzy");\n      const confidence = matchType === "estimated" ? 0.62 : matchType === "fuzzy" ? 0.84 : 1;\n      setResult(next);\n      setSearchResult({ device, matchType, confidence, correctedQuery: matchType === "fuzzy" ? `${device.brand} ${device.model}` : undefined, source: device.id.startsWith("generated-") ? "estimated" : "database", sensitivity: next, createdAt });')

# Improve display of search correction metadata in the result footer.
s = s.replace('<span>UPDATED JUST NOW</span></div></div>', '<span>{searchResult?.matchType === "fuzzy" ? `GỢI Ý: ${searchResult.correctedQuery}` : searchResult?.matchType === "estimated" ? "ESTIMATED CONFIG" : "EXACT DEVICE MATCH"}</span></div></div>')

p.write_text(s)
