from pathlib import Path
p = Path('/home/ubuntu/do-nhay-ff-sua/client/src/pages/Home.tsx')
s = p.read_text()

# Add durable domain types after Sensitivity.
needle = '''type Sensitivity = {\n  general: number;\n  redDot: number;\n  scope2x: number;\n  scope4x: number;\n  sniper: number;\n  camera360: number;\n  fireButton: number;\n  dpi: number;\n};\n'''
addition = needle + '''\ntype SearchResult = { device: Device; source: "database" | "estimated"; sensitivity: Sensitivity; createdAt: string; };\ntype SavedConfig = { deviceId: string; deviceName: string; brand: string; profile: string; fps: number; general: number; redDot: number; scope2x: number; scope4x: number; sniper: number; camera360: number; fireButton: number; dpi: number; createdAt: string; };\ntype HistoryItem = SavedConfig;\ntype FavoriteItem = { deviceId: string; deviceName: string; createdAt: string; };\n\nfunction loadJson<T>(key: string, fallback: T): T {\n  if (typeof window === "undefined") return fallback;\n  try { return JSON.parse(localStorage.getItem(key) || "null") ?? fallback; } catch { return fallback; }\n}\n\nfunction toHistoryItems(value: unknown): HistoryItem[] {\n  if (!Array.isArray(value)) return [];\n  return value.flatMap((item): HistoryItem[] => {\n    if (typeof item === "object" && item && "deviceId" in item && "deviceName" in item) return [item as HistoryItem];\n    if (typeof item === "string") {\n      const device = devices.find((entry) => entry.model === item || `${entry.brand} ${entry.model}` === item);\n      return device ? [{ deviceId: device.id, deviceName: `${device.brand} ${device.model}`, brand: device.brand, profile: "Kéo tâm", fps: 144, general: 0, redDot: 0, scope2x: 0, scope4x: 0, sniper: 0, camera360: 0, fireButton: 0, dpi: 470, createdAt: new Date().toISOString() }] : [];\n    }\n    return [];\n  });\n}\n\nfunction toFavoriteItems(value: unknown): FavoriteItem[] {\n  if (!Array.isArray(value)) return [];\n  return value.flatMap((item): FavoriteItem[] => {\n    if (typeof item === "object" && item && "deviceId" in item && "deviceName" in item) return [item as FavoriteItem];\n    if (typeof item === "string") {\n      const device = devices.find((entry) => entry.id === item);\n      return device ? [{ deviceId: device.id, deviceName: `${device.brand} ${device.model}`, createdAt: new Date().toISOString() }] : [];\n    }\n    return [];\n  });\n}\n'''
if 'type SearchResult' not in s:
    s = s.replace(needle, addition)

# State types and initializers.
s = s.replace('  const [result, setResult] = useState<Sensitivity | null>(null);', '  const [result, setResult] = useState<Sensitivity | null>(null);\n  const [searchResult, setSearchResult] = useState<SearchResult | null>(null);')
s = s.replace('  const [history, setHistory] = useState<string[]>(() => { try { return JSON.parse(localStorage.getItem("sua-history") || "[]"); } catch { return []; } });\n  const [favorites, setFavorites] = useState<string[]>(() => { try { return JSON.parse(localStorage.getItem("sua-favorites") || "[]"); } catch { return []; } });', '  const [history, setHistory] = useState<HistoryItem[]>(() => toHistoryItems(loadJson("sua-history", [])));\n  const [favorites, setFavorites] = useState<FavoriteItem[]>(() => toFavoriteItems(loadJson("sua-favorites", [])));')

# History local persistence and selected favorite helper.
s = s.replace('  const matches = useMemo(() => devices.map((device) => ({ device, score: fuzzyScore(debouncedQuery, device) })).filter((item) => item.score > 0).sort((a, b) => b.score - a.score).slice(0, 4), [debouncedQuery]);', '  const matches = useMemo(() => devices.map((device) => ({ device, score: fuzzyScore(debouncedQuery, device) })).filter((item) => item.score > 0).sort((a, b) => b.score - a.score).slice(0, 4), [debouncedQuery]);\n  const isFavorite = Boolean(selectedDevice && favorites.some((item) => item.deviceId === selectedDevice.id));')

# Analyze creates a durable result and config tied to the searched device.
s = s.replace('      setResult(next); setProfileDevice(device);\n      localStorage.setItem("sua-profile-committed", "1");\n      setLoading(false); setHistory((old) => [device.model, ...old.filter((item) => item !== device.model)].slice(0, 5));', '''      const createdAt = new Date().toISOString();\n      setResult(next);\n      setSearchResult({ device, source: device.id.startsWith("generated-") ? "estimated" : "database", sensitivity: next, createdAt });\n      setProfileDevice(device);\n      localStorage.setItem("sua-profile-committed", "1");\n      const saved: SavedConfig = { deviceId: device.id, deviceName: `${device.brand} ${device.model}`, brand: device.brand, profile, fps, general: next.general, redDot: next.redDot, scope2x: next.scope2x, scope4x: next.scope4x, sniper: next.sniper, camera360: next.camera360, fireButton: next.fireButton, dpi: next.dpi, createdAt };\n      setLoading(false);\n      setHistory((old) => [saved, ...old.filter((item) => item.deviceId !== device.id)].slice(0, 5));''')

# Clear search must clear SearchResult too.
s = s.replace('setSelectedDevice(null); setResult(null); setPreviousResult(null);', 'setSelectedDevice(null); setSearchResult(null); setResult(null); setPreviousResult(null);')

# Replace favorite/share handler.
old = '''  const toggleFavorite = () => { if (!selectedDevice) return; setFavorites((old) => old.includes(selectedDevice.id) ? old.filter((item) => item !== selectedDevice.id) : [...old, selectedDevice.id]); toast.success(favorites.includes(selectedDevice.id) ? "Đã bỏ khỏi yêu thích" : "Đã lưu vào yêu thích"); };\n  const share = async () => { if (!selectedDevice) return; const shareText = `Độ nhạy FF SÚA — ${selectedDevice.brand} ${selectedDevice.model}`; if (navigator.share) await navigator.share({ title: "Độ Nhạy FF SÚA", text: shareText }); else { await navigator.clipboard?.writeText(shareText); toast.success("Đã copy nội dung chia sẻ"); } };'''
new = '''  const toggleFavorite = () => {\n    if (!selectedDevice) return;\n    const next = { deviceId: selectedDevice.id, deviceName: `${selectedDevice.brand} ${selectedDevice.model}`, createdAt: new Date().toISOString() };\n    setFavorites((old) => old.some((item) => item.deviceId === next.deviceId) ? old.filter((item) => item.deviceId !== next.deviceId) : [next, ...old]);\n    toast.success(isFavorite ? "Đã bỏ khỏi yêu thích" : "Đã lưu vào yêu thích");\n  };\n  const share = async () => {\n    if (!selectedDevice) return;\n    const url = `${window.location.origin}/result?device=${encodeURIComponent(selectedDevice.id)}`;\n    window.history.pushState({}, "", `/result?device=${encodeURIComponent(selectedDevice.id)}`);\n    const shareText = `Độ nhạy FF SÚA — ${selectedDevice.brand} ${selectedDevice.model}\\n${url}`;\n    if (navigator.share) await navigator.share({ title: "Độ Nhạy FF SÚA", text: shareText, url }); else { await navigator.clipboard?.writeText(url); toast.success("Đã copy link cấu hình"); }\n  };\n  useEffect(() => {\n    const deviceId = new URLSearchParams(window.location.search).get("device");\n    const device = deviceId ? devices.find((entry) => entry.id === deviceId) : null;\n    if (device) { setQuery(`${device.brand} ${device.model}`); analyze(device); }\n  }, []);'''
if old not in s:
    raise SystemExit('favorite/share block not found')
s = s.replace(old, new)

# Favorite button predicates.
s = s.replace('favorites.includes(selectedDevice.id)', 'isFavorite')

# History/favorites persistence shape and rendering.
s = s.replace('history.map((item, index) => <button key={`${item}-${index}`} onClick={() => { const device = devices.find((entry) => entry.model === item); if (device) { selectDevice(device); analyze(device); } }}><span className="activity-number">0{index + 1}</span><span><strong>{item}</strong><small>Độ nhạy FF • vừa xong</small></span><ArrowRight size={15} /></button>)', 'history.map((item, index) => <button key={`${item.deviceId}-${index}`} onClick={() => { const device = devices.find((entry) => entry.id === item.deviceId) || createFallbackDevice(item.deviceName); setQuery(item.deviceName); analyze(device); }}><span className="activity-number">0{index + 1}</span><span><strong>{item.deviceName}</strong><small>{item.profile} · {item.fps} FPS · DPI {item.dpi}</small></span><ArrowRight size={15} /></button>)')
s = s.replace('history.length} lần tìm gần nhất', 'history.length} lần tìm gần nhất')
s = s.replace('favorites.length ? <div className="favorite-list">{favorites.map((id) => { const device = devices.find((item) => item.id === id); return device ? <button key={id} onClick={() => { selectDevice(device); analyze(device); }}><span className="favorite-dot" style={{ background: device.accent }} /><span>{device.brand} {device.model}</span><ArrowRight size={15} /></button> : null; })}</div>', 'favorites.length ? <div className="favorite-list">{favorites.map((item) => { const device = devices.find((entry) => entry.id === item.deviceId); return device ? <button key={item.deviceId} onClick={() => { selectDevice(device); analyze(device); }}><span className="favorite-dot" style={{ background: device.accent }} /><span>{item.deviceName}</span><ArrowRight size={15} /></button> : null; })}</div>')

# Use searchResult as the result-card source guard and device authority.
s = s.replace('(loading || (selectedDevice && result))', '(loading || searchResult)')

p.write_text(s)
