from pathlib import Path

home = Path('/home/ubuntu/do-nhay-ff-sua/client/src/pages/Home.tsx')
text = home.read_text()
text = text.replace('  CircleHelp,\n', '  CircleHelp,\n  CheckCircle2,\n')
text = text.replace('  const [query, setQuery] = useState("");\n', '  const [query, setQuery] = useState("");\n  const [debouncedQuery, setDebouncedQuery] = useState("");\n')
text = text.replace('  const [result, setResult] = useState<Sensitivity>(() => generateSensitivity(devices[0], "Kéo tâm", 144, "M1887", 470));\n', '  const [result, setResult] = useState<Sensitivity>(() => generateSensitivity(devices[0], "Kéo tâm", 144, "M1887", 470));\n  const [previousResult, setPreviousResult] = useState<Sensitivity | null>(null);\n')
text = text.replace('  const matches = useMemo(() => devices.map((device) => ({ device, score: fuzzyScore(query, device) })).filter((item) => item.score > 0).sort((a, b) => b.score - a.score).slice(0, 4), [query]);\n', '  useEffect(() => { const timer = window.setTimeout(() => setDebouncedQuery(query), 180); return () => window.clearTimeout(timer); }, [query]);\n  const matches = useMemo(() => devices.map((device) => ({ device, score: fuzzyScore(debouncedQuery, device) })).filter((item) => item.score > 0).sort((a, b) => b.score - a.score).slice(0, 4), [debouncedQuery]);\n')
text = text.replace('  const updateChoice = (type: "profile" | "fps" | "weapon" | "dpi", value: string | number) => {', '  const updateSensitivity = (key: keyof Sensitivity, value: number) => { setPreviousResult(result); setResult((old) => ({ ...old, [key]: value })); };\n  const updateChoice = (type: "profile" | "fps" | "weapon" | "dpi", value: string | number) => {')
old_rows = '{sensitivityLabels.map(([key, label]) => <div className="sensitivity-row" key={key}><span>{label}</span><div className="sensitivity-track"><span style={{ width: `${result[key] / 2}%` }} /></div><strong>{result[key]}</strong></div>)}'
new_rows = '{sensitivityLabels.map(([key, label]) => <div className="sensitivity-row" key={key}><span>{label}</span><div className="sensitivity-control"><div className="sensitivity-track"><span style={{ width: `${result[key] / 2}%` }} /></div><input className="sensitivity-range" aria-label={`Chỉnh ${label}`} type="range" min="0" max="200" value={result[key]} onChange={(event) => updateSensitivity(key, Number(event.target.value))} /></div><strong>{result[key]}</strong></div>)}'
text = text.replace(old_rows, new_rows)
confidence = '<div className="confidence-block"><div className="confidence-copy"><span>ĐỘ TIN CẬY DỮ LIỆU</span><strong>{selectedDevice.score}%</strong></div><div className="confidence-track"><span style={{ width: `${selectedDevice.score}%` }} /></div><small><CheckCircle2 size={13} /> {selectedDevice.score >= 94 ? "Thông số thiết bị đã biết" : "Một phần thông số được thuật toán ước lượng"}</small></div>'
text = text.replace('<div className="sensitivity-list">', confidence + '<div className="sensitivity-list">')
profile = '''      <section className="container profile-strip" id="profile-summary"><div className="profile-intro"><div className="profile-avatar">S</div><div><p className="eyebrow"><span className="eyebrow-line" /> CẤU HÌNH CỦA TÔI</p><h2>Hồ sơ SÚA</h2><p>Reload web vẫn giữ thiết bị và preset bạn đang dùng.</p></div></div><div className="profile-stat"><span>THIẾT BỊ HIỆN TẠI</span><strong>{selectedDevice.brand} {selectedDevice.model}</strong><small>{selectedDevice.tier} · {selectedDevice.refreshRate}Hz</small></div><div className="profile-stat"><span>CẤU HÌNH ĐANG DÙNG</span><strong>{profile}</strong><small>{fps} FPS · DPI {result.dpi}</small></div><div className="profile-stat"><span>CẤU HÌNH ĐÃ LƯU</span><strong>{favorites.length}</strong><small>{history.length} lần tìm gần nhất</small></div></section>\n\n'''
text = text.replace('      <section className="container lower-grid" id="library">', profile + '      <section className="container compare-section" id="compare"><div className="section-heading compact"><div><p className="eyebrow"><span className="eyebrow-line" /> SO SÁNH / DELTA VIEW</p><h2>Cấu hình hiện tại ↔ đề xuất</h2></div><span className="compare-note">Thay đổi được highlight</span></div><div className="compare-grid">{sensitivityLabels.slice(0, 6).map(([key, label]) => { const baseline = previousResult?.[key] ?? result[key]; const delta = result[key] - baseline; return <div className="compare-row" key={key}><span>{label}</span><strong className={delta ? "compare-changed" : ""}>{baseline}</strong><ArrowRight size={14} /><strong className={delta ? "compare-changed" : ""}>{result[key]}</strong><small>{delta > 0 ? `+${delta}` : delta || "—"}</small></div>; })}<div className="compare-row"><span>DPI</span><strong>{previousResult?.dpi ?? 470}</strong><ArrowRight size={14} /><strong className={result.dpi !== (previousResult?.dpi ?? 470) ? "compare-changed" : ""}>{result.dpi}</strong><small>{result.dpi - (previousResult?.dpi ?? 470) > 0 ? `+${result.dpi - (previousResult?.dpi ?? 470)}` : result.dpi - (previousResult?.dpi ?? 470) || "—"}</small></div></div></section>\n\n      <section className="container lower-grid" id="library">')
text = text.replace('<button onClick={() => navTo("library")}>Lịch sử & yêu thích</button>', '<button onClick={() => navTo("library")}>Lịch sử & yêu thích</button><button onClick={() => navTo("vault")}>Cloud Vault</button>')
home.write_text(text)

index = Path('/home/ubuntu/do-nhay-ff-sua/client/index.html')
html = index.read_text()
html = html.replace('<meta name="theme-color" content="#080b0d" />', '<meta name="theme-color" content="#080b0d" />\n    <link rel="manifest" href="/manifest.json" />\n    <link rel="apple-touch-icon" href="/icon.svg" />') if 'theme-color' in html else html.replace('<title>', '<meta name="theme-color" content="#080b0d" />\n    <link rel="manifest" href="/manifest.json" />\n    <title>')
index.write_text(html)
