from pathlib import Path
p = Path('/home/ubuntu/do-nhay-ff-sua/client/src/pages/Home.tsx')
s = p.read_text()

start = s.index('function generateSensitivity(device: Device, profile: string, fps: number, weapon: string, dpi: number): Sensitivity {')
end = s.index('\n\nfunction Logo()', start)
engine = '''function clamp(value: number, min = 0, max = 200) {\n  return Math.max(min, Math.min(max, Math.round(value)));\n}\n\nfunction calculateRecommendedDpi(device: Device, profile: string) {\n  let dpi = 440;\n  if (device.refreshRate <= 60) dpi += 15;\n  else if (device.refreshRate >= 120) dpi -= 5;\n  if (device.touchSampling >= 1000) dpi += 15;\n  else if (device.touchSampling > 0 && device.touchSampling < 200) dpi -= 5;\n  if (device.type === "TABLET") dpi -= 10;\n  if (profile === "Ổn định") dpi -= 15;\n  if (profile === "Kéo tâm") dpi += 15;\n  if (profile === "Headshot") dpi += 20;\n  return clamp(dpi, 300, 600);\n}\n\nfunction generateSensitivity(device: Device, profile: string, fps: number, weapon: string, dpi: number): Sensitivity {\n  let base = 150;\n  if (device.refreshRate >= 144) base += 12;\n  else if (device.refreshRate >= 120) base += 8;\n  else if (device.refreshRate >= 90) base += 3;\n  else if (device.refreshRate <= 60) base -= 4;\n  if (device.touchSampling >= 1000) base += 8;\n  else if (device.touchSampling >= 500) base += 4;\n  else if (device.touchSampling > 0 && device.touchSampling < 200) base -= 4;\n  if (device.type === "TABLET") base -= 4;\n  if (device.tier === "GAMING") base += 5;\n  else if (device.tier === "FLAGSHIP") base += 2;\n  else if (device.tier === "BUDGET") base -= 3;\n  const fpsModifier: Record<number, number> = { 60: -4, 90: 0, 120: 3, 144: 5, 165: 6 };\n  base += fpsModifier[fps] ?? 0;\n  const profileModifier: Record<string, number> = { "Ổn định": -5, "Cân bằng": 0, "Kéo tâm": 7, Headshot: 9 };\n  base += profileModifier[profile] ?? 0;\n  if (weapon === "M1887") base += 2;\n  if (weapon === "MP40") base += 1;\n  return {\n    general: clamp(base + 10),\n    redDot: clamp(base),\n    scope2x: clamp(base - 5),\n    scope4x: clamp(base - 10),\n    sniper: clamp(base - 65),\n    camera360: clamp(base + 12),\n    fireButton: clamp(50 + Math.round((base - 140) * 0.08), 45, 70),\n    dpi: clamp(dpi || calculateRecommendedDpi(device, profile), 300, 600),\n  };\n}\n'''
s = s[:start] + engine + s[end:]

# Add engine details and smart adjustment state/handlers.
s = s.replace('  const [previousResult, setPreviousResult] = useState<Sensitivity | null>(null);', '  const [previousResult, setPreviousResult] = useState<Sensitivity | null>(null);\n  const [feedback, setFeedback] = useState<string | null>(null);')
s = s.replace('  const updateSensitivity = (key: keyof Sensitivity, value: number) => { if (!result) return; setPreviousResult(result); setResult((old) => old ? ({ ...old, [key]: value }) : old); };', '''  const updateSensitivity = (key: keyof Sensitivity, value: number) => { if (!result) return; setPreviousResult(result); setResult((old) => old ? ({ ...old, [key]: value }) : old); };\n  const adjustSensitivity = (delta: number) => { if (!result) return; setPreviousResult(result); setResult((old) => old ? Object.fromEntries(Object.entries(old).map(([key, value]) => [key, key === "dpi" ? value : clamp(Number(value) + delta)])) as Sensitivity : old); };\n  const submitFeedback = (value: string) => { setFeedback(value); localStorage.setItem("sua-feedback", JSON.stringify({ value, deviceId: selectedDevice?.id, createdAt: new Date().toISOString() })); toast.success("Đã ghi nhận phản hồi của bạn"); };''')
# Analyze recommended DPI for a new search instead of carrying a prior device's DPI.
s = s.replace('const next = generateSensitivity(device, profile, fps, weapon, dpi);', 'const engineDpi = calculateRecommendedDpi(device, profile);\n      setDpi(engineDpi);\n      const next = generateSensitivity(device, profile, fps, weapon, engineDpi);')

# Insert explanation and DPI tiers after sensitivity list closing.
marker = '</div><div className="result-footer"><span><Activity size={15} /> ENGINE PRESET: {profile.toUpperCase()}</span>'
insert = '''</div><div className="dpi-presets"><div><span>ỔN ĐỊNH</span><strong>{Math.max(300, result.dpi - 20)}</strong></div><div className="dpi-active"><span>CÂN BẰNG</span><strong>{result.dpi}</strong></div><div><span>KÉO TÂM</span><strong>{Math.min(600, result.dpi + 20)}</strong></div></div><div className="engine-reasons"><p className="eyebrow">VÌ SAO CẤU HÌNH NÀY ĐƯỢC CHỌN?</p><div><span>✓ Màn hình {selectedDevice.refreshRate}Hz</span><span>✓ {selectedDevice.tier === "GAMING" ? "Thiết bị gaming" : "Thiết bị hiệu năng " + selectedDevice.tier.toLowerCase()}</span><span>✓ FPS {fps}</span><span>✓ Profile {profile}</span></div><small>Cấu hình được tạo bởi Sensitivity Engine, có thể cần tinh chỉnh theo thói quen cá nhân.</small></div><div className="result-footer"><span><Activity size={15} /> ENGINE PRESET: {profile.toUpperCase()}</span>'''
s = s.replace(marker, insert)
# Add adjustment and feedback controls before panel actions.
marker2 = '<div className="panel-actions"><button className="primary-action" onClick={copyResult}>'
insert2 = '<div className="smart-adjust"><label>ĐIỀU CHỈNH THÔNG MINH</label><div><button onClick={() => adjustSensitivity(5)}>NHẠY HƠN</button><button onClick={() => adjustSensitivity(0)}>CÂN BẰNG</button><button onClick={() => adjustSensitivity(-5)}>KIỂM SOÁT</button></div></div><div className="panel-actions"><button className="primary-action" onClick={copyResult}>'
s = s.replace(marker2, insert2)
# Add feedback after compare section block before lower grid.
needle = '\n\n      <section className="container lower-grid" id="library">'
feedback_section = '''\n\n      {selectedDevice && result && <section className="container feedback-section"><div><p className="eyebrow"><span className="eyebrow-line" /> LEARNING / FEEDBACK</p><h3>Cấu hình này phù hợp với bạn?</h3></div><div className="feedback-actions"><button className={feedback === "Không phù hợp" ? "feedback-active" : ""} onClick={() => submitFeedback("Không phù hợp")}>Không phù hợp</button><button className={feedback === "Khá ổn" ? "feedback-active" : ""} onClick={() => submitFeedback("Khá ổn")}>Khá ổn</button><button className={feedback === "Phù hợp" ? "feedback-active" : ""} onClick={() => submitFeedback("Phù hợp")}>Phù hợp</button></div></section>'''
s = s.replace(needle, feedback_section + needle)

p.write_text(s)
